Ensure every path is interpreted as a utf-8 string
cpcloud/protoletariat pull request #67
Opened 2021-12-03 04:51 UTC by shawwn

I'm using Click 7.1.2. For some reason, the input file paths were `bytes` instead of `str`.

This PR fixed the problem for me. It's probably a safe thing to merge, and it guards against other strange Click incompatibilities.

In case it matters, here's how I was invoking `protol`:

https://github.com/shawwn/tensorflow-checkpoint-reader/blob/c8a77dc82c88f52971f11a96e59d5ace7b595611/build.sh#L15-L16

2021-12-03 05:45 UTC, cpcloud requested changes
Thanks for doing this! Can you add a `fix:` prefix to the next commit message title? I honestly wasn't expecting contributors so soon so I haven't written anything about contributing, so please bear with me.

2021-12-03 05:45 UTC, cpcloud commented on protoletariat/fdsetgen.py
> +def _utf8(x) -> str:
Can you remove this function and instead replace the calls with `os.fsdecode`? https://docs.python.org/3/library/os.html#os.fsdecode

2021-12-03 16:14 UTC, cpcloud commented
@shawwn I am able to reproduce this with click 7.1.2. How is it that you're using `protol` with a different version of click than what's specified it its dependencies? `protol` requires `click >=8.0.1,<9`.

2021-12-03 17:15 UTC, cpcloud commented
@shawwn This looks like a bug in click 7.1.2, where it's not respecting the value of `path_type` when using `click.Path(..., path_type=pathlib.Path)`.

Adding this subcommand to `protoletariat`

```python
@main.command(help="test")
@click.argument("path", type=click.Path(path_type=Path))
@click.pass_context
def test(ctx: click.Context, path: Path):
    print(f"{type(path)}: {path}")
```

Click 7.1.2:

```
❯ echo foo | xargs -L1 -I {} protol -o ../tensorflow/gen test {}
xargs: warning: options --max-lines and --replace/-I/-i are mutually exclusive, ignoring previous --max-lines value
<class 'bytes'>: b'foo'
```

Click 8.0.1:

```
❯ echo foo | xargs -L1 -I {} protol -o ../tensorflow/gen test {}
xargs: warning: options --max-lines and --replace/-I/-i are mutually exclusive, ignoring previous --max-lines value
<class 'pathlib.PosixPath'>: foo
```

Still would like to know how you're able to run `protol` using Click 7.1.2 in the first place :)

2021-12-04 01:58 UTC, shawwn commented
For every new tool, I clone its repo to ~/ml and then run python3 setup.py develop. That way when things inevitably go wrong, I can debug it in pycharm. It’s a super underrated workflow.

I basically live in the IDE and don’t feel comfortable running things I can’t debug. Poetry’s philosophy of no setup.py / pip install -e . is really unfortunate.

In this case, my tool [tpunicorn](https://github.com/shawwn/tpunicorn) uses click 7.1.2. I work a lot nowadays and don’t have time to update it to the latest click. Which means if I tried to install your tool, it would have caused problems with mine.

There are plenty of ways to deal with this, but all of them seem to require a monstrous amount of space and complexity (separate venvs) and make it far harder to drop into an IDE debugger (hello pdb).

I like your os.fsdecode() trick. I’ll be sure to use that from now on whenever I need to convert anything to utf-8, not just paths. ;)

I’ll get around to this eventually.

2021-12-04 02:02 UTC, shawwn commented
And thank you for solving the protobuf relative import problem. I was able to port the entire tensorflow codebase’s protobufs to my tensorflow checkpoint reader project; protol worked perfectly on the first try, once the utf8 problem was fixed. (The only minor annoyance was that protoc accepts python_out whereas protol requires python-out, hyphenated. I wasn’t sure what was wrong until I studied —help.)

Before protol, I was manually fixing imports by hand. It wasn’t too bad, but it was a pain.

2021-12-04 04:51 UTC, shawwn commented
Ok, I've made the requested changes (and tested them). Let me know if there's anything else.

2021-12-04 14:24 UTC, cpcloud commented
@shawwn

> I’ll be sure to use that from now on whenever I need to convert anything to utf-8, not just paths

I don't think I'd recommend that, since that function is only for decoding paths to `str` if they're `bytes`, not for generic `bytes` decoding :)

2021-12-04 14:24 UTC, cpcloud approved these changes

2021-12-04 14:24 UTC, merged

2021-12-04 14:41 UTC, cpcloud commented
@shawwn This is in v0.6.2. Thanks again.

2021-12-24 02:14 UTC, shawwn commented
> @shawwn
> 
> > I’ll be sure to use that from now on whenever I need to convert anything to utf-8, not just paths
> 
> I don't think I'd recommend that, since that function is only for decoding paths to `str` if they're `bytes`, not for generic `bytes` decoding :)

Amusingly, I looked into how it's implemented under the hood, and it really is just a shorthand for decoding strings as utf-8.

At least on posix. But if (by luck) Windows happens to do the same thing, then I'm totally using this to troll whoever reads my code.

2021-12-24 02:45 UTC, cpcloud commented
I think it's more complicated than that, no? See https://docs.python.org/3/library/os.html#python-utf-8-mode and https://docs.python.org/3/c-api/init_config.html#c.PyConfig.filesystem_encoding

2021-12-24 04:49 UTC, shawwn commented
According to the docs, the default seems to be utf-8 on all platforms. Linux is omitted, but after SSH'ing into a few random servers and checking, `locale.getpreferredencoding()` always seems to be utf-8.

You've convinced me to put an `assert locale.getpreferredencoding() == 'UTF-8'` at the top of my main file though, next to `__version__`. :)

Also, grepping for `utf8_mode` in cpython revealed:

```
Misc/NEWS.d/3.8.0a4.rst
1027:Fix test_utf8_mode on VxWorks: Python always use UTF-8 on VxWorks.
```

If Python is making sure that utf-8 is the default even on VxWorks, I think it's safe to say that utf-8 won, and any non-utf-8 filesystem should be thought of as a bug.

Counterexamples welcome!

2021-12-24 12:56 UTC, cpcloud commented
Well, that is great news @shawwn. Thanks for the explanation!